### ISSUE TITLE
Unable to connect to Kubernetes cluster

### ISSUE THREAD

**Issue by TheShadyyDev** [tijaniabdellatif/microservices-k8s-ecommerce#9]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/64221094/217511188-d2fadb9b-0150-4adc-9250-a93974e84151.png">

**Comment by tijaniabdellatif** [comment]
I suggest to make a meeting once you'are free 

Suggest the timestamp in comment @TheShadyyDev

**Comment by tijaniabdellatif** [comment]
I will let the meet link here it's a global link to be used in any time decided : 
@mmerguoum @shaimeur @TheShadyyDev 

## Link : 
[Meeting](https://meet.google.com/qws-cbti-jrg)

**Comment by TheShadyyDev** [comment]
I'll be free at 7:00 PM

**Comment by shaimeur** [comment]
fine 7pm then

**Comment by tijaniabdellatif** [comment]
@TheShadyyDev @shaimeur  , I willl not be able to be on the meeting today, but tomorrow at the same time i'll be there 

Sorry for the delay 

Thank you

**Comment by shaimeur** [comment]
it's ok tomorrow then

**Comment by tijaniabdellatif** [comment]
@everyone, Sorry for my delay, i'm almost free, we should close that issue

**Comment by tijaniabdellatif** [comment]
Done
